"""add big title attribute to big data model

Revision ID: 25d98db85d0a
Revises: c8b89403ffc1
Create Date: 2025-10-28 13:46:16.910194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d98db85d0a'
down_revision: Union[str, None] = 'c8b89403ffc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_data_results', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('big_data_results', 'title')
    # ### end Alembic commands ###
