"""add analysis column

Revision ID: 4b283d47ed01
Revises: 25d98db85d0a
Create Date: 2025-10-28 15:08:42.250657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b283d47ed01'
down_revision: Union[str, None] = '25d98db85d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_data_results', sa.Column('analysis_results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('big_data_results', 'analysis_results')
    # ### end Alembic commands ###
