"""Set datetime attribute on starttime and endtime

Revision ID: 571be0dcf9cf
Revises: 6935911a3e76
Create Date: 2025-09-20 12:52:07.102757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571be0dcf9cf'
down_revision: Union[str, None] = '6935911a3e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "start_date",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="start_date::timestamp with time zone",
        existing_nullable=False,
    )

    op.alter_column(
        "subscriptions",
        "end_date",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="end_date::timestamp with time zone",
        existing_nullable=False,
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
